CREATE TABLE IF NOT EXISTS game_types (
    type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_name VARCHAR(50),
    type_description text DEFAULT 'No Description has been provided'
);

CREATE TABLE IF NOT EXISTS card_squares (
    square_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    square TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS square_type_rel (
    square_id INT NOT NULL REFERENCES card_squares(square_id),
    type_id INT NOT NULL REFERENCES game_types(type_id)
);

CREATE TYPE STATUS as ENUM ('Start Scheduled', 'Awaiting Start', 'Running', 'Finished');

CREATE TABLE IF NOT EXISTS games (
    game_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type_id INT NOT NULL REFERENCES game_types(type_id),
    is_scheduled BOOLEAN NOT NULL,
    game_start timestamp(0),
    game_length interval(0) NOT NULL,
    game_pin VARCHAR(10),
    game_owner INT NOT NULL,
    game_status STATUS
);

CREATE TABLE IF NOT EXISTS player_info (
    player_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    discord_id INT NOT NULL,
    game_id INT NOT NULL REFERENCES games(game_id)
);

CREATE TABLE IF NOT EXISTS card_info (
    player_id INT REFERENCES player_info(player_id),
    square_id INT REFERENCES card_squares(square_id),
    square_position INT NOT NULL,
    square_status BOOLEAN DEFAULT FALSE
);


INSERT INTO game_types (type_id, type_name, type_description) VALUES (0, 'Shared', 'The data associated with this type is shared across all games. It should never be run as a game itself');

INSERT INTO card_squares (square_id, square) VALUES (0, 'Free Space');

INSERT INTO square_type_rel (type_id, square_id) VALUES (0,0);